### ISSUE TITLE
Feature: Password

### ISSUE THREAD

**Issue by Apollo-11** [kksng/leda#46]
## Feature request

Создать новый компонент L.Password

Компонент будет использован в формах регистрации.
Компонент состоит из одного поля ввода и блока с информационными сообщениями под ним.

![image](https://user-images.githubusercontent.com/7481588/75772202-87816500-5d5c-11ea-847a-b6fb70307eb5.png)

По умолчанию текст в поле ввода замаскирован звёздочками и в поле ввода отображается иконка «закрытый глаз».
При клике на иконку с глазом маскировка символов снимается, иконка меняется на «открытый глаз» и пользователь может увидеть пароль. При повторном клике маскировка возвращается.

По умолчанию под компонентом выводится текст с информацией о требованиях к паролю. Должен быть текст по умолчанию и возможность настраивать его через атрибут passwordRulesRender. 

Функция «сгенерировать пароль» доступна через passwordRulesRender и настраивается в родительском приложении.

Текст с информацией о требованиях к паролю выводится, если в компонент введено 3 и менее символов. Если введено 4 и более символа, происходит оценка пароля на предмет его устойчивости к взлому. Таким образом количество символов, с которого начинать оценку пароля, по умолчанию равно 4. Это число можно задать через атрибут minPasswordEvaluationLength. Если задано 0, оценка сложности пароля начинается сразу при фокусировке, и выводится соответсвующее сообщение.

Если пользователь ввёл минимальное количество символов, необходимое для оценки пароля, текст под полем ввода меняется на текст с оценкой сложности пароля: Слабый пароль, Надёжный пароль, Отличный пароль.

Настройка внешнего вида текста с оценкой сложности производится через атрибут passwordEvaluationRender. Атрибут принимает стандартные аргументы, аргумент elementProps должен содержать поле с информацией о текущей сложности пароля.

Оценка сложности пароля происходит при каждом вызове onChange, соответственно меняется и сообщение.

Оценка сложности пароля происходит по правилам:
для Надёжного пароля не меньше восьми символов, обязательно должны быть буквы латинского алфавита и цифры. Правило можно переопределить через атрибут passwordEvaluator;
для Отличного пароля правила уточняются;

Правила оценки надёжности пароля могут быть заданы через passwordEvaluator.

Атрибут passwordEvaluator принимает массив объектов с типом PasswordEvaluator. Порядок следования элементов в массиве имеет значение.
Первый элемент массива относится к Слабому паролю, который не соответствует никаким правилам надёжности. Первый объект не содержит поле evaluator, но содержит текст, который выводится для паролей, которые не соответствуют требованиям надёжности.
Второй и последующий элементы массива содержат как текст, так и правила оценки. Каждая следующая проверка не включает в себя предыдущую, поэтому проверки предыдущего уровня должны быть явно включены в родительском приложении в проверки более высокого уровня.

Валидация компонента происходит по стандартным правилам. Это значит, что по умолчанию валидация в компоненте не включена. Валидация включается при наличии обязательных атрибутов form и name и необязательных isRequired и vlidator. Для валидации паролей должен быть создан готовый валидатор «password», который валидирует по правилам для Надёжного пароля (см. выше) и выводит готовое сообщение (см. макет).

Блок с иконкой глаза кастомизируется через атрибут passwordVisibilityRender, в elementProps должно быть поле isVisible, которое говорит о том, в каком режиме находится компонент.

Блок с иконкой глаза находится правее поля ввода, которое может содержать другие иконки, например для очистки поля ввода.

Компонент должен поддерживать все атрибуты, которые поддерживает L.Input. 

При нажатии на Enter компонент теряет фокус и переносит его в поле для повтора пароля (при наличии). Это поведение может быть предопределено через атрибут onEnterPress.

L.Password
  passwordRulesRender
  passwordEvaluationRender
  passwordVisibilityRender
  minPasswordEvaluationLength
  passwordEvaluator

Interface PassworEvaluator
  evaluator?: RegExp | (any) => boolean,
  evaluationMessage: string

====

Поле для повтора пароля. (Реализуется после полной готовности основного компонента).

Назначение компонента - проверить идентичность паролей.

Компонент можно привязать к основному компоненту через атрибут repeats, который принимает строку с именем основного компонента для ввода пароля:

L.Password
  form=‘passwordForm'
  name=‘checkPassword'
  repeats=‘mainPasswordComponentName'

На каждое изменение значения в компоненте (onChange) происходит валидация компонента и выводится сообщение об ошибке, если пароли не совпадают. При потере фокуса и сабмите формы также происходит валидация.

Настройка сообщения об ошибке происходит через invalidMessageRender, остальные атрибуты валидации игнорируются.

При нажатии на Enter происходит валидация и сабмит формы. Это поведение может быть переопределено через атрибут onEnterPress.

====

Оба компонента должны поддерживать атрибут theme.

Тесты.

Документация.

По вопросам внешнего вида и вёрстки см. макет.

**Comment by roshal** [comment]
https://jira.esphere.ru/browse/FEND-873
